[id]
name = flare_splunk_app
version = 1.0.2

[ui]
is_visible = 1
label = Flare
supported_themes = light,dark

[launcher]
author = Flare
description = Flare Splunk Application
version = 1.0.2

[package]
check_for_updates = 1
id = flare_splunk_app

[install]
is_configured = 0
build = 3

[triggers]
reload.splunk_create = simple
