############################################################
# Flare CTEM - CIM Tags
############################################################

# Base: All Flare events are alerts
[eventtype=flare_alert]
alert = enabled
threat = enabled

# Ransom Leak
[eventtype=flare_ransomleak]
alert = enabled
threat = enabled

# Stealer Log
[eventtype=flare_stealer_log]
alert = enabled
threat = enabled
malware = enabled

# Credit Card
[eventtype=flare_cc]
alert = enabled
threat = enabled

# Lookalike Domain
[eventtype=flare_lookalike]
alert = enabled
threat = enabled
network = enabled

# Blog Post
[eventtype=flare_blog_post]
alert = enabled
threat = enabled

# Chat Message
[eventtype=flare_chat_message]
alert = enabled
threat = enabled

# Forum Post
[eventtype=flare_forum_post]
alert = enabled
threat = enabled

# Paste
[eventtype=flare_paste]
alert = enabled
threat = enabled

# Listing
[eventtype=flare_listing]
alert = enabled
threat = enabled

# Bucket
[eventtype=flare_bucket]
alert = enabled
threat = enabled
cloud = enabled

# Social Media Account
[eventtype=flare_social_media]
alert = enabled
threat = enabled
