services:
  splunk:
    image: splunk/splunk:9.3
    container_name: splunk
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=a_password
    volumes:
      - ./output/flare:/opt/splunk/etc/apps/flare
      - ./splunk/default.yml:/tmp/defaults/default.yml