services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=a_password
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
    volumes:
      - ./output/flare:/opt/splunk/etc/apps/flare
      - ./splunk/default.yml:/tmp/defaults/default.yml
      - ./logs:/opt/splunk/var/log/splunk
