#!/usr/bin/env bash

set -eo pipefail
shopt -s inherit_errexit

#####################################################################################
############################## Generate Dependencies ################################
#####################################################################################
### This script is used to retrieve the dependencies used by the Splunk app,      ###
### retrieve the versions from the python-integrations resolve's requirements.txt ###
### and generate our own small requirements.txt to download the dependencies via  ###
### pip and finally move them to our git ignored                                  ###
#####################################################################################

usage() {
  echo "Usage: $(basename "$0") [-c] [--cleanup]"
  echo "    -l, --local: generate symlinks to the dependencies"
  echo "    -c, --cleanup: deletes the symlinks and the temp folders"
  echo "    -p, --production: move the download dependencies inside the bin folder of the application"
  exit 1
}

CLEAN_UP=0
SPLUNK_VENDOR_FOLDER="flare_splunk_integration/bin/vendor"

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      usage
      ;;
    -c|--cleanup)
      shift
      CLEAN_UP=1
      break
      ;;
    *)
      echo "Unknown argument $1"
      exit 1
      ;;
  esac
done
set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

log() {
    local MESSAGE=$1
    local GREEN='\e[32m'
    local NO_COLOR='\e[0m'
    echo -e "${GREEN}${MESSAGE}${NO_COLOR}"
}

errorlog() {
    local MESSAGE=$1
    local RED='\e[31m'
    local NO_COLOR='\e[0m'
    echo -e "${RED}${MESSAGE}${NO_COLOR}"
}

cleanup() {
    log "Cleaning old env"
    rm -rf "${SPLUNK_VENDOR_FOLDER}"
    mkdir "${SPLUNK_VENDOR_FOLDER}"
}

cleanup

if [ "$CLEAN_UP" = "1" ]; then
    log "All done!"
    exit 0
fi

log "Download dependencies in the bin folder of Splunk"
pip install --target "${SPLUNK_VENDOR_FOLDER}" -r requirements.txt

log "Deleting the dist-info, bin and __pycache__ folders"
find "${SPLUNK_VENDOR_FOLDER}" -type d -name "*.dist-info" -exec rm -r {} +
rm -rf "${SPLUNK_VENDOR_FOLDER:?}/bin"
rm -rf "${SPLUNK_VENDOR_FOLDER}/__pycache__"