[id]
name = flare
version = 1.0.0

[ui]
is_visible = 1
label = Flare
supported_themes = light,dark

[launcher]
author = Splunk
description = Flare
version = 1.0.0

[package]
check_for_updates = 0
id = flare

[install]
is_configured = 0
build = 1

[triggers]
reload.splunk_create = simple