[script://$SPLUNK_HOME/etc/apps/flare/bin/cron_job_ingest_events.py]
disabled = true
index = flare
interval = 86400
python.version = python3
python.required = 3.13
source = flare
sourcetype = flare_json
passAuth = splunk-system-user