[script:flare_validate_api_key]
match=/validate_api_key
handler=flare_external_requests.FlareValidateApiKey
python.version = python3
python.required = 3.13

[script:flare_user_tenants]
match=/fetch_user_tenants
handler=flare_external_requests.FlareUserTenants
python.version = python3
python.required = 3.13

[script:flare_severity_filters]
match=/fetch_severity_filters
handler=flare_external_requests.FlareSeverityFilters
python.version = python3
python.required = 3.13

[script:flare_source_type_filters]
match=/fetch_source_type_filters
handler=flare_external_requests.FlareSourceTypeFilters
python.version = python3
python.required = 3.13

[script:flare_search_events]
match=/fetch_search_events
handler=flare_external_requests.FlareSearchEvents
python.version = python3
python.required = 3.13