[expose:flare_validate_api_key]
pattern=validate_api_key
methods=POST

[expose:flare_user_tenants]
pattern=fetch_user_tenants
methods=POST

[expose:flare_severity_filters]
pattern=fetch_severity_filters
methods=POST

[expose:flare_source_type_filters]
pattern=fetch_source_type_filters
methods=POST

[expose:flare_search_events]
pattern=fetch_search_events
methods=POST
