name: Publish Splunk Application to Splunkbase

on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codebase
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.9'

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Build and package
              run: |
                  make package

            - name: Publish to Splunkbase
              run: |
                  SPLUNKBASE_CREDS='${{ secrets.SPLUNKBASE_CREDS }}' make publish
